# Generated by Django 4.0.2 on 2022-02-18 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_quizBiblio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'Ce titre est déjà utilisé.'}, max_length=60, unique=True, verbose_name='titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('time', models.IntegerField(default=0, verbose_name='time')),
                ('is_creator', models.BooleanField(default=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApps.quiz')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='theme1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_theme', to='quizApps.theme', verbose_name='1er thème'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='theme2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_theme', to='quizApps.theme', verbose_name='2nd thème (Facultatif)'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.ManyToManyField(related_name='quiz', through='quizApps.UserQuiz', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='question')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('explication', models.TextField(blank=True, null=True, verbose_name='Explication')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizApps.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propositionText', models.CharField(max_length=255, verbose_name='proposition')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Est correcte')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quizApps.question')),
            ],
        ),
    ]
