# Generated by Django 4.0.2 on 2022-07-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='theme1',
            new_name='first_theme',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='theme2',
            new_name='second_theme',
        ),
    ]
