# Generated by Django 3.2.1 on 2021-05-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionText',
            field=models.CharField(max_length=255, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time'),
        ),
    ]
