# Generated by Django 3.2.1 on 2021-06-16 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizApps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApps.question'),
        ),
    ]
