# Generated by Django 3.2.1 on 2021-07-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApps', '0002_auto_20210702_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Requis. Saisir une adresse email valide.', max_length=254, unique=True),
        ),
    ]
