# Generated by Django 3.2.1 on 2021-06-18 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizApps', '0002_alter_proposition_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_prop', to='quizApps.proposition'),
        ),
    ]
