# Generated by Django 3.2.1 on 2021-07-05 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizApps', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='theme',
        ),
        migrations.AddField(
            model_name='quiz',
            name='theme1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first_theme', to='quizApps.theme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='theme2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_theme', to='quizApps.theme'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(error_messages={'unique': 'Ce titre est déjà utilisé.'}, max_length=60, unique=True, verbose_name='titre'),
        ),
    ]
