# Generated by Django 3.2.1 on 2021-06-18 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizApps', '0003_question_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizApps.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='correct_prop', to='quizApps.proposition'),
        ),
    ]
