# Generated by Django 3.2.1 on 2021-06-19 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizApps', '0004_auto_20210618_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizApps.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./', verbose_name='image'),
        ),
    ]
