# Generated by Django 4.0.2 on 2022-07-08 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_quizBiblio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
    ]
